import type { Metadata } from "next";
import { karnxTheme } from "./theme";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { AuthProvider } from "./context/AuthContext";
import '@/public/styles/global.css'

export const metadata: Metadata = {
  title: "Welcome to Karnx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body suppressHydrationWarning>
        <ThemeProvider theme={karnxTheme}>
          <AuthProvider>
              <CssBaseline />
              {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
